name: Create and test backports tar

on:
  release:
    types: [published]

jobs:
  create_tar:
    name: Create backports tar
    runs-on: ubuntu-latest

    steps:
      - name: Install coccinelle
        run: |
          sudo apt update
          sudo apt install -y coccinelle

      - name: Checkout backports
        uses: actions/checkout@v4
        with:
          path: backports

      - name: Clone linux
        shell: bash
        run: |
          git clone --depth 1 --branch ${{ github.event.release.tag_name }} https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git linux

      - name: Generate backports tar
        working-directory: backports
        run: ./gentree.py --refresh ${GITHUB_WORKSPACE}/linux ${GITHUB_WORKSPACE}/backports-${{ github.event.release.tag_name }}

      - name: Check for git changes
        working-directory: backports
        run: git diff

      - name: Pack backports tar
        run: tar cJf backports-${{ github.event.release.tag_name }}.tar.xz backports-${{ github.event.release.tag_name }}

      - name: Upload backports tar
        uses: svenstaro/upload-release-action@v1-release
        with:
          file: backports-${{ github.event.release.tag_name }}.tar.xz
          asset_name: backports-${{ github.event.release.tag_name }}.tar.xz
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
